const express = require("express");
const router = express.Router();

const userRoutes = require("./../domains/user");
const OTPRoutes = require("./../domains/otp");
const EmailVerificationRoutes = require("./../domains/email_verification");
const ForgotPasswordRoutes = require("./../domains/forgot_password");
const AccountRoutes = require("./../domains/account");
const TokenAccountRoutes = require("./../domains/tokenAccount");
const SeedPhraseRoutes = require("./../domains/seedPhrase");
const BlockRoutes = require("./../domains/block");
const TransactionRoutes = require("./../domains/transaction");
const TokenRoutes = require("./../domains/token");
const GamerTagRoutes = require("./../domains/gamer_tag");
const FighterRoutes = require("./../domains/fighter");
const StakeRoutes = require("./../domains/stake");
const BlockchainRoutes = require("./../domains/blockchain");
const ValidatorRoutes = require("./../domains/validator");
const TitleRoutes = require("./../domains/title");
const VRTAccountRoutes = require("./../domains/vrtAccount");
const VRTRoutes = require("./../domains/vrt");

router.use("/user", userRoutes);
router.use("/otp", OTPRoutes);
router.use("/email_verification", EmailVerificationRoutes);
router.use("/forgot_password", ForgotPasswordRoutes);
router.use("/account", AccountRoutes);
router.use("/tokenAccount", TokenAccountRoutes);
router.use("/gamer_tag", GamerTagRoutes);
router.use("/seedPhrase", SeedPhraseRoutes);
router.use("/block", BlockRoutes);
router.use("/transaction", TransactionRoutes);
router.use("/token", TokenRoutes);
router.use("/block", BlockRoutes);
router.use("/fighter", FighterRoutes);
router.use("/stake", StakeRoutes);
router.use("/blockchain", BlockchainRoutes);
router.use("/validator", ValidatorRoutes);
router.use("/title", TitleRoutes);
router.use("/vrtAccount", VRTAccountRoutes);
router.use("/vrt", VRTRoutes);

module.exports = router;
